# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('asset_type', models.CharField(max_length=20)),
                ('asset_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeClassRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=20)),
                ('asset_class', models.CharField(max_length=20)),
            ],
        ),
    ]
