# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:09
from __future__ import unicode_literals

from django.db import migrations, models

def load_restrictions(apps, schema_editor):
    Restrictions = apps.get_model("api", "AssetTypeClassRestrictions")
    Restrictions.objects.create(asset_type="satellite", asset_class="dove")
    Restrictions.objects.create(asset_type="satellite", asset_class="rapideye")
    Restrictions.objects.create(asset_type="antenna", asset_class="dish")
    Restrictions.objects.create(asset_type="antenna", asset_class="yagi")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load_restrictions),
    ]
